# Generated by Django 2.2.7 on 2019-11-12 20:43

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=1)),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=1, validators=[game.models.validate_unique_tag])),
                ('row', models.IntegerField(validators=[game.models.validate_row_range])),
                ('col', models.IntegerField(validators=[game.models.validate_col_range])),
            ],
        ),
    ]
