# Generated by Django 2.2.7 on 2019-11-19 21:34

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='tag',
            field=models.CharField(max_length=1, validators=[game.models.validate_unique_tag, game.models.validate_num_players]),
        ),
    ]
